### ISSUE TITLE
web-app step 5 model.greeting <h2></h2>

### ISSUE THREAD

**Issue by xpat** [mchat/tutorials#2]
On` http://mariechatfield.com/tutorials/web-app/step5.html, the instructions read 
>  Let’s render model.greeting in our template for the route. `<h2></h2>`

But it should read: `<h2>{{model.greeting}}</h2>,` as it does on Github.  The tutorial (as presented on the website) is missing {{model.greeting}}.

**Comment by mariechatfield** [comment]
Ah good catch! Looks like I forgot to escape that content.
